server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/west2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1324657980
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        min-idle: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true
